"""Constants for Proxmox Custom Sensors integration."""

DOMAIN = "proxmox_sensors"

# Connection settings
CONF_HOST = "host"
CONF_USER = "user"                 # E.g.: root@pam or monitor@pbs
CONF_PASSWORD = "password"         # API Token secret or user password
CONF_TOKEN_ID = "token_id"         # Token Name (e.g., ha-token)
CONF_TOKEN_SECRET = "token_secret" # The Secret generated by Proxmox

# Server configuration
CONF_NODE = "node"                 # Target node name
CONF_PLATFORM_TYPE = "platform_type"
CONF_SENSORS = "sensors"

# Supported server types
SERVER_PVE = "PVE"
SERVER_PBS = "PBS"

# Additional configuration attributes 
CONF_VERIFY_SSL = "verify_ssl"
CONF_PORT = "port"
